# Generated by Django 4.2.5 on 2023-09-17 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IfcTask',
            fields=[
                ('status', models.CharField(max_length=255)),
                ('GlobalId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
