# Generated by Django 4.2.5 on 2023-09-21 09:47

from django.db import migrations, models
import django.db.models.deletion
import project.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IfcProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LongDescription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IfcTaskTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DurationType', models.CharField(choices=[('ET', 'Elapsed Time'), ('WT', 'Work Time'), ('ND', 'Not Defined')], default='WT', max_length=3)),
                ('ScheduleStart', models.DateTimeField(blank=True, null=True)),
                ('ScheduleFinish', models.DateTimeField(blank=True, null=True)),
                ('EarlyStart', models.DateTimeField(blank=True, null=True)),
                ('EarlyFinish', models.DateTimeField(blank=True, null=True)),
                ('LateStart', models.DateTimeField(blank=True, null=True)),
                ('LateFinish', models.DateTimeField(blank=True, null=True)),
                ('FreeFloat', models.DurationField(blank=True, null=True)),
                ('TotalFloat', models.DurationField(blank=True, null=True)),
                ('IsCritical', models.BooleanField(default=False)),
                ('StatusTime', models.DateTimeField(blank=True, null=True)),
                ('ActualDuration', models.DurationField(blank=True, null=True)),
                ('ActualStart', models.DateTimeField(blank=True, null=True)),
                ('ActualFinish', models.DateTimeField(blank=True, null=True)),
                ('RemainingTime', models.DurationField(blank=True, null=True)),
                ('Completition', models.FloatField(default=0.0)),
            ],
            bases=(project.models.IfcSchedulingTime, models.Model),
        ),
        migrations.CreateModel(
            name='IfcRelSequence',
            fields=[
                ('GlobalId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('TimeLag', models.DurationField(blank=True, null=True)),
                ('SequenceType', models.CharField(choices=[('FF', 'Finish Finish'), ('FS', 'Finish Start'), ('SF', 'Start Finish'), ('SS', 'Start Start'), ('UD', 'User Defined'), ('ND', 'Not Defined')], default='FS', max_length=2)),
                ('UserDefinedSequenceType', models.CharField(blank=True, max_length=255, null=True)),
                ('RelType', models.CharField(choices=[('PD', 'Predecessor'), ('SS', 'Successor')], default='SS', max_length=11)),
                ('RelatedProcess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelatedProcess', to='project.ifcprocess')),
                ('RelatingProcess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelatingProcess', to='project.ifcprocess')),
            ],
        ),
        migrations.AddField(
            model_name='ifcprocess',
            name='PredecessorSucessor',
            field=models.ManyToManyField(through='project.IfcRelSequence', to='project.ifcprocess'),
        ),
        migrations.CreateModel(
            name='IfcTask',
            fields=[
                ('ifcprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='project.ifcprocess')),
                ('GlobalId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('ObjectType', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(max_length=255)),
                ('WorkMethod', models.CharField(blank=True, max_length=255, null=True)),
                ('IsMilestone', models.BooleanField(default=False)),
                ('Priority', models.IntegerField(default=0)),
                ('TaskType', models.CharField(choices=[('adj', 'Adjustment'), ('att', 'Attendance'), ('cal', 'Calibration'), ('con', 'Construction'), ('dem', 'Demolition'), ('dis', 'Dismantle'), ('dsp', 'Disposal'), ('emg', 'Emergency'), ('ins', 'Inspection'), ('int', 'Installation'), ('log', 'Logistic'), ('man', 'Maintenace'), ('mov', 'Move'), ('opr', 'Operation'), ('rem', 'Removal'), ('ren', 'Renovation'), ('saf', 'Safety'), ('shu', 'Shutdown'), ('sta', 'Startup'), ('tes', 'Testing'), ('tbl', 'Troubleshooting'), ('usr', 'User Defined'), ('ndf', 'Not Defined')], default='con', max_length=3)),
                ('TaskTime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.ifctasktime')),
            ],
            bases=('project.ifcprocess',),
        ),
    ]
