# Generated by Django 4.2.5 on 2023-09-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ifctask',
            old_name='status',
            new_name='Status',
        ),
        migrations.AddField(
            model_name='ifctask',
            name='Name',
            field=models.CharField(default='Taylor', max_length=255),
            preserve_default=False,
        ),
    ]
