# Generated by Django 4.2.5 on 2023-09-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_ifctask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifctask',
            name='ObjectType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='IfcRelSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeLag', models.DurationField(blank=True, null=True)),
                ('SequenceType', models.CharField(choices=[('FF', 'Finish Finish'), ('FS', 'Finish Start'), ('SF', 'Start Finish'), ('SS', 'Start Start'), ('UD', 'User Defined'), ('ND', 'Not Defined')], default='FS', max_length=2)),
                ('UserDefinedSequenceType', models.CharField(blank=True, max_length=255, null=True)),
                ('RelatedProcess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelatedProcess', to='project.ifctask')),
                ('RelatingProcess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelatingProcess', to='project.ifctask')),
            ],
        ),
    ]
