# Generated by Django 4.2.5 on 2023-09-18 08:42

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_ifctask_ifctasktype_ifctask_ismilestone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfcTaskTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DurationType', models.CharField(choices=[('ET', 'Elapsed Time'), ('WT', 'Work Time'), ('ND', 'Not Defined')], default='WT', max_length=3)),
                ('ScheduleStart', models.DateTimeField(blank=True, null=True)),
                ('ScheduleFinish', models.DateTimeField(blank=True, null=True)),
                ('EarlyStart', models.DateTimeField(blank=True, null=True)),
                ('EarlyFinish', models.DateTimeField(blank=True, null=True)),
                ('LateStart', models.DateTimeField(blank=True, null=True)),
                ('LateFinish', models.DateTimeField(blank=True, null=True)),
                ('FreeFloat', models.DurationField(blank=True, null=True)),
                ('TotalFloat', models.DurationField(blank=True, null=True)),
                ('IsCritical', models.BooleanField(default=False)),
                ('StatusTime', models.DateTimeField(blank=True, null=True)),
                ('ActualDuration', models.DurationField(blank=True, null=True)),
                ('ActualStart', models.DateTimeField(blank=True, null=True)),
                ('ActualFinish', models.DateTimeField(blank=True, null=True)),
                ('RemainingTime', models.DurationField(blank=True, null=True)),
                ('Completition', models.FloatField(default=0.0)),
            ],
            bases=(project.models.IfcSchedulingTime, models.Model),
        ),
        migrations.RemoveField(
            model_name='ifctask',
            name='IfcTaskType',
        ),
        migrations.AddField(
            model_name='ifctask',
            name='TaskType',
            field=models.ManyToManyField(to='project.ifctasktime'),
        ),
    ]
