# Generated by Django 4.2.5 on 2023-09-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_ifctasktime_remove_ifctask_ifctasktype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifctask',
            name='TaskTime',
            field=models.ManyToManyField(to='project.ifctasktime'),
        ),
        migrations.RemoveField(
            model_name='ifctask',
            name='TaskType',
        ),
        migrations.AddField(
            model_name='ifctask',
            name='TaskType',
            field=models.CharField(choices=[('adj', 'Adjustment'), ('att', 'Attendance'), ('cal', 'Calibration'), ('con', 'Construction'), ('dem', 'Demolition'), ('dis', 'Dismantle'), ('dsp', 'Disposal'), ('emg', 'Emergency'), ('ins', 'Inspection'), ('int', 'Installation'), ('log', 'Logistic'), ('man', 'Maintenace'), ('mov', 'Move'), ('opr', 'Operation'), ('rem', 'Removal'), ('ren', 'Renovation'), ('saf', 'Safety'), ('shu', 'Shutdown'), ('sta', 'Startup'), ('tes', 'Testing'), ('tbl', 'Troubleshooting'), ('usr', 'User Defined'), ('ndf', 'Not Defined')], default='con', max_length=3),
        ),
    ]
