# Generated by Django 4.2.5 on 2023-09-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_ifctask_tasktime_remove_ifctask_tasktype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifctask',
            name='TaskTime',
        ),
        migrations.AddField(
            model_name='ifctask',
            name='TaskTime',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ifctasktime'),
        ),
    ]
